version: '3.1'

services:
  node-red:
    image: nodered/node-red-docker
    volumes:
      - nodered:/data
      - '.:/data/node_modules/node-red-contrib-telegrambot-switches'
    ports:
      - 1880:1880

volumes:
  nodered: {}
